image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

lint-and-test:
  stage: test
  script:
    - pnpm install
    - pnpm add -D esbuild
    - pnpm test
    - pnpm lint
    - pnpm build-all

# Deploy docs to Gitlab pages
pages:
  stage: deploy
  only:
    - master
  script:
    - pnpm install
    - pnpm docs
    - mv docs public
  artifacts:
    paths:
      - public
